# Settings
output: '/tmp/mw2md'
authors_csv: 'authors.csv'
wiki_xml: 'dump.xml'
history: true
output_subdir: 'source'

# Regular expression of pages to skip
skip: '^(user|user talk|talk|template|mediawiki):'

# Assign category (& directory) based on filename
# (it will stop on the first match, so order matters)
catmatch:
  #"workshop": event/workshop
  #"event": event
  #"how[ -]?to": howto
  #"api": api
  #"guide": documentation

# Rewrite filenames
rewrite_file:
  #"how[ -]?to[ -]?": ""

# Rewrite directories
rewrite_dir:
  #"features": "feature"
  #"home/feature": "feature"
  #"infra.*": "infra"
  #"how-to": "howto"
  #"releases": "release"

# Rewrite directory and filename after everything above is processed
# (catch-all)
rewrite_full:
  "^category/(.*).html.md": '\1/index.html.md'
  #"project-proposal/": "project/proposal/"
  #"/project-proposal-": "/"
  #"^draft-documentation/": "documentation/draft/"
  #"^projects/": "project/"
  #"^how-to/": "howto/"
  #"^(development)-(environment)/": '\1/\2/'
  #"^(building)-(engine)/": '\2/\1/'

# Match original wikitext and add metadata to frontmatter
frontmatter:
  #'\{\{Feature\|[^}]*name=([^\|}]*)[^}]*\}\}': "feature_name"
  #'\{\{Feature\|[^}]*modules=([^\|}]*)[^}]*\}\}': "feature_modules"
  #'\{\{Feature\|[^}]*status=([^\|}]*)[^}]*\}\}': "feature_status"

# Rewrite special wiki constructs to be markdown-friendly
# (output should be HTML that feeds into the Markdown conversion)
rewrite_wiki:
  '\{\{#ev:youtube\|([^|}]*)\|([^|}]*)\}\}': '<iframe width="\2" src="//youtube.com/embed/\1" frameborder="0" allowfullscreen="true"> </iframe>'
  '\{\{#ev:youtube\|([^|}]*)\|([^|}]*)\|([^|}]*)[^}]?\}\}': '<iframe width="\2" src="//youtube.com/embed/\1" frameborder="0" align="\3" allowfullscreen="true"> </iframe>'

# Rewrite resulting Markdown
rewrite_markdown:
  # Fix dd-indented bullets
  '^:\\\* ':   '    * '
  '^::\\\* ':  '        * '
  '^:::\\\* ': '            * '
  # Fix dd-indentent numbered lists
  '^:# ':   '    1. '
  '^::# ':  '        1. '
  '^:::# ': '            1. '
  # Fix bolding not getting translated
  "'''([^']*)'''": '**\\1**'
  # Fix empty lines with trailing space
  # (as often seen in code blocks)
  '^\s+$': ''
  # Fix username (oVirt-specific)
  #'<username>': '&lt;username&gt;'

# Keep track of specific warnings,
# for pages that might need extra attention
warnings:
  '<references>': 'references'
  '<\/ref>': 'references'
  '\|style\=': 'table-style'
  '\|colspan\=': 'table-colspan'
  '\|width\=': 'table-width'
  '^\:\*': 'list-item?'
